[package]
name = "wx" # the name of the package
version = "0.2.0"    # the current version, obeying semver
authors = ["KENZ.gelsoft@gmail.com"]

build = "./build.rs"

[dependencies] 
libc = "0.2.*"

[build-dependencies]
cc = "1.0.*"
bindgen = "0.55.*"

